### ISSUE TITLE
作者你好 

### ISSUE THREAD

**Issue by ChristingLi** [ghwghw4/GICXMLLayout#2]
从Android转学IOS开发,比较喜欢这种xml的形式解析,有个问题想问一下,Router 生成的页面不能以VC的方式提供出来吗?  代码不精进,希望指教一二

**Comment by ghwghw4** [comment]
UIViewController *vc = [GICXMLLayout parseElementFromPath:path withParentElement:nil];

**Comment by ghwghw4** [comment]
前提是path对应的XML文件的根节点是page

**Comment by ChristingLi** [comment]
感谢回复.
我一直看返回值是个Id 并没有找到UIViewController的返回....
多谢指点
