### ISSUE TITLE
[提问] Android 端是否有相应的开源方案

### ISSUE THREAD

**Issue by ChengLuffy** [ghwghw4/GICXMLLayout#4]
首先感谢开源 GICXMLLayout，公司团队计划尝试跟进。

团队希望 Android/iOS 两端体验尽量一致，请问Android 端应用开发是否有对应的方案或替代方案？

谢谢。

**Comment by ghwghw4** [comment]
方案是有的，而且也已经调研过了，但是目前作者时间有限，短时间内无法提供安卓版的实现。另外，考虑到这个库一开始是为iOS单独开发的，因此如果要做到跨平台，那么有些元素的属性就有可能会改动，而对JS支持的那部分的原理在安卓上也是通用的，主要是UI、布局部分需要安卓单独适配开发。

**Comment by ChengLuffy** [comment]
ok
